spring:
  application:
    name: myportfolio
  data:
    mongodb:
      uri: mongodb+srv://qualitygroups24:vUywKrmgc3bQfkC4@myportfolio.xqwjz.mongodb.net/?retryWrites=true&w=majority&appName=myportfolio
      database: myportfolio
server:
  port: 8081
